# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - monitor_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - monitor_network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  monitor_network:
    driver: bridge